[interfaces]

  # SX1262 is configured and added programmatically by reticulum_node.py
  # Add any other interfaces here (TCP backbone, etc.)

  [[RNS Backbone]]
    type = TCPClientInterface
    enabled = yes
    target_host = rns.noderage.org
    target_port = 4242
