"""
Console script: sx1262-install-rns-interface

Installs the SX1262ReticulumInterface.py wrapper into ~/.reticulum/interfaces/,
writes a starter ~/.reticulum/config if one does not already exist, and writes
a starter ~/.reticulum/telemetry_beacon.conf if one does not already exist.

Usage:
    sx1262-install-rns-interface
"""

import os
import sys


WRAPPER_CONTENT = '''\
# Auto-generated by sx1262-install-rns-interface
# Re-run that command after upgrading sx1262_driver to refresh this file.

from sx1262_driver.reticulum_interface import SX1262ReticulumInterface

interface_class = SX1262ReticulumInterface
'''

TELEMETRY_CONF = '''\
# sx1262-telemetry-beacon configuration
# One argument per line (argparse fromfile format: flag then value on next line).
# This file is loaded automatically when you run sx1262-telemetry-beacon.
# Edit the values below to match your location.

--lat
0.0
--lon
0.0
--alt
0
--name
MyPi
# --collector
# REPLACE_WITH_32_HEX_CHAR_COLLECTOR_HASH
--interval
300
'''

RETICULUM_CONFIG = '''\
[reticulum]
  enable_transport = no
  share_instance = yes
  shared_instance_port = 37428
  instance_control_port = 37429
  panic_on_interface_error = no
  discoverable = yes

[interfaces]

  [[RNS Backbone]]
    type = TCPClientInterface
    enabled = yes
    target_host = rns.noderage.org
    target_port = 4242

  [[SX1262 LoRa Interface]]
    type = SX1262ReticulumInterface
    enabled = yes
    name = sx1262_lora
    frequency = 914875000
    bandwidth = 125000
    spreading_factor = 9
    coding_rate = 5
    sync_word = 0x1424
    preamble_length = 18
    spi_bus = 0
    spi_device = 0
    reset_pin = 18
    busy_pin = 20
    irq_pin = -1
    nss_pin = 21
    use_irq = false
'''


def main():
    reticulum_dir = os.path.expanduser("~/.reticulum")
    interfaces_dir = os.path.join(reticulum_dir, "interfaces")
    os.makedirs(interfaces_dir, exist_ok=True)

    # Always refresh the wrapper (safe to overwrite — it's auto-generated)
    wrapper_dest = os.path.join(interfaces_dir, "SX1262ReticulumInterface.py")
    with open(wrapper_dest, "w") as f:
        f.write(WRAPPER_CONTENT)
    print(f"Installed: {wrapper_dest}")

    # Only write config if it doesn't already exist
    config_dest = os.path.join(reticulum_dir, "config")
    if not os.path.exists(config_dest):
        with open(config_dest, "w") as f:
            f.write(RETICULUM_CONFIG)
        print(f"Created:   {config_dest}")
    else:
        print(f"Skipped:   {config_dest} (already exists — edit manually if needed)")
        print("\nEnsure ~/.reticulum/config contains an [[SX1262 LoRa Interface]] section.")
        print("See RETICULUM_CONFIG in sx1262_driver/install_rns_interface.py for reference.")

    # Only write telemetry config if it doesn't already exist
    telemetry_conf_dest = os.path.join(reticulum_dir, "telemetry_beacon.conf")
    if not os.path.exists(telemetry_conf_dest):
        with open(telemetry_conf_dest, "w") as f:
            f.write(TELEMETRY_CONF)
        print(f"Created:   {telemetry_conf_dest}")
        print("           Edit it to set your coordinates, name, and collector hash.")
    else:
        print(f"Skipped:   {telemetry_conf_dest} (already exists)")


if __name__ == "__main__":
    main()
