"""
Console script: sx1262-install-rns-interface

Installs the SX1262ReticulumInterface.py wrapper into ~/.reticulum/interfaces/
so that Reticulum can load the SX1262 interface from its config file.

Usage:
    sx1262-install-rns-interface
"""

import os
import shutil
import sys


WRAPPER_CONTENT = '''\
# Auto-generated by sx1262-install-rns-interface
# Re-run that command after upgrading sx1262_driver to refresh this file.

from sx1262_driver.reticulum_interface import SX1262ReticulumInterface
'''

CONFIG_EXAMPLE = '''\

# Add this to ~/.reticulum/config under [interfaces]:
#
#   [[SX1262 LoRa Interface]]
#     type = SX1262ReticulumInterface
#     enabled = yes
#     name = sx1262_lora
#     frequency = 914875000
#     bandwidth = 125000
#     spreading_factor = 9
#     coding_rate = 5
#     sync_word = 0x1424
#     preamble_length = 18
#     spi_bus = 0
#     spi_device = 0
#     reset_pin = 18
#     busy_pin = 20
#     irq_pin = -1
#     nss_pin = 21
#     use_irq = false
'''


def main():
    interfaces_dir = os.path.expanduser("~/.reticulum/interfaces")
    os.makedirs(interfaces_dir, exist_ok=True)

    dest = os.path.join(interfaces_dir, "SX1262ReticulumInterface.py")
    with open(dest, "w") as f:
        f.write(WRAPPER_CONTENT)

    print(f"Installed: {dest}")
    print(CONFIG_EXAMPLE)


if __name__ == "__main__":
    main()
